services:
  frontend:
    container_name: frontend
    image: ${ACR_NAME}.azurecr.io/${WEBAPP_NAME}-frontend
    ports:
      - "80:80"

  backend:
    container_name: backend
    image: ${ACR_NAME}.azurecr.io/${WEBAPP_NAME}-backend
